name: Build Github Pages
on: [push, pull_request]
env:
  PIP: python -m pip
  SPHINX: python -m sphinx --color
jobs:
  configure-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
  build-pages:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: configure-pages
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
        sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    - name: Double-check Python version
      run: |
        python --version
    - name: Install Python package
      run: |
        $PIP install .[docs]
    - name: Build HTML
      run: |
        $SPHINX docs/ ./_site
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
    - name: Deploy artifact
      id: deployment
      uses: actions/deploy-pages@v3

#  deploy:
#      runs-on: ubuntu-latest
#      needs: build-pages
